In [18]:
import numpy as np
import pandas as pd

import seaborn as sns
import env as env

In [34]:
csv_export_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTV226o37uIYGsG9BSUI5OoXb9xWtLTbJBib8kEj7hgV7KzuvaxHrB6Kp2BpcYKTgNTCwpsbc1AKheV/pub?gid=0&single=true&output=csv'
df_googlesheet = pd.read_csv(csv_export_url)
df_googlesheet.head(1)

,NAME,PRICE,SERVINGS,SERVING SIZE,PROTEIN,TOTAL WT,Unnamed: 6,PROTEIN PRICE,TOTAL PROTEIN,TYPE
0,Raw,$79.97,90.0,25g,21g,5.00 lb.,NaN,$0.042,1890,Concentrate

In [27]:
grassfed_whey = pd.crosstab(df_googlesheet['TYPE'], df_googlesheet['SERVING SIZE'])

In [28]:
grassfed_whey

SERVING SIZE  25g  29g  30g  31g  41g
TYPE
Blend           0    0    1    1    0
Concentrate     2    0    1    0    1
Isolate         0    1    2    0    0

In [38]:
xls = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'
xls = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
adam = pd.read_csv(xls)
adam.head(1)

,NAME,PRICE,SERVINGS,SERVING SIZE,PROTEIN,TOTAL WT,Unnamed: 6,PROTEIN PRICE,TOTAL PROTEIN,TYPE
0,Raw,$79.97,90.0,25g,21g,5.00 lb.,NaN,$0.042,1890,Concentrate

In [39]:
adam

,NAME,PRICE,SERVINGS,SERVING SIZE,PROTEIN,TOTAL WT,Unnamed: 6,PROTEIN PRICE,TOTAL PROTEIN,TYPE
0,Raw,$79.97,90.0,25g,21g,5.00 lb.,NaN,$0.042,1890,Concentrate
1,Whey Fantastic,$79.95,75.0,30g,25g,5.00 lb.,NaN,$0.043,1875,Blend
2,BN Labs Organic,$94.99,72.0,30g,24g,5.00 lb.,NaN,$0.055,1728,Concentrate
3,AGN Roots,$69.00,47.0,29g,25g,3.00 lb.,NaN,$0.059,1175,Isolate
4,Orgain Whey,$26.99,20.0,41g,21g,1.82 lb.,NaN,$0.064,420,Concentrate
5,MariGold Isolate,$52.99,31.0,30g,26g,2.05 lb.,NaN,$0.066,806,Isolate
6,Molk,$44.95,31.0,31g,22g,2lb,NaN,$0.066,682,Blend
7,Opportuniteas Isolate,$28.99,15.0,30g,28g,1lb,NaN,$0.069,420,NaN
8,Antler Farms NZ Isolate,$59.99,30.0,30g,27g,2.00 lb.,NaN,$0.074,810,Isolate
9,Antler Farms NZ,$59.99,30.0,30g,26g,2.00 lb.,NaN,$0.077,780,NaN
10,Garden of Life Sport,$41.16,20.0,32g,24g,2.47lb,NaN,$0.086,480,NaN
11,Norcal Organic,$64.99,36.0,25g,21g,2.00 lb.,NaN,$0.086,756,Concentrate
12,Legion Isolate,$59.99,30.0,32g,23g,1.91 lb.,NaN,$0.087,690,NaN
13,Natural Force A2,$29.99,16.9,27g,20g,1.00 lb.,NaN,$0.089,338,NaN
14,Protein 17 Organic,$39.00,15.0,30g,24g,1.00 lb.,NaN,$0.108,360,NaN
15,Teraswhey,$27.94,12.0,28g,21g,.75 lb.,NaN,$0.111,252,NaN
16,Garden of Life Organic,$29.30,12.0,32g,21g,.83 lb.,NaN,$0.116,252,NaN
17,Dr. Kellyann Bone Broth,$79.00,30.0,27g,21g,1.80 lb.,NaN,$0.125,630,NaN